<?php

namespace App;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-08 07:44:52
 * zip name 20220408074322_0LC5qX8nQ0T.zip
 */

class MyApp {
    const datetime = [
        'created_at'  => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];
}

/*
//app
//config/app.php -> this file

'aliases' => [
  //...
  'MyApp' => AppMyApp::class,
*/