<?php

namespace App\Models;

use App\MyApp;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-09 08:16:51
 * zip name 20220409081629_CDLdyDoy0EJ.zip
 */

class BarangModel extends Model
{
    use HasFactory;
    protected $table = "barang";
    protected $fillable = ["name", "created_at", "updated_at"];
    protected $casts = MyApp::datetime;

    //ClassModel::with('other_table')->get();
    //public function other_table(){
    //    return $this->belongsTo(OtherTable::class, 'id_in_BarangModel', 'id_in_other_table');
    //}

    //ClassModel::with('other_table')->get();
    //public function other_table(){
    //    return $this->hasMany(OtherTable::class, 'id_in_other_table', 'id_in_BarangModel');
    //}
    
    //ClassModel::with('other_table')->get();
    //public function other_table(){
    //    return $this->hasOne(OtherTable::class, 'id_in_other_table', 'id_in_BarangModel');
    //}
}
